<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Terms of Service - ArtemisShield</title>

    <!-- Styles -->
    @include('partials.styles')
</head>
<body class="boxed-size">
    @include('partials.preloader')
    @include('partials.sidebar')

    <div class="container-fluid">
        <div class="main-content d-flex flex-column">
            <!-- Start Header Area -->
            @include('partials.header')
            <!-- End Header Area -->

            <!--  START: Terms of Service Content  -->
            <div class="container my-5">
                <div class="row justify-content-center">
                    <div class="col-md-10">
                        <div class="card shadow-sm">
                            <div class="card-body p-4 p-md-5">
                                <h1 class="card-title text-center mb-4">Terms of Service</h1>
                                <h2 class="h5 text-muted text-center mb-5">ArtemisShield - Wildfire Protection Dashboard</h2>

                                <p>Welcome to ArtemisShield. By accessing or using this dashboard, you agree to be bound by these terms. This system is a professional decision-support tool intended for authorized and trained personnel in emergency and wildfire management. Its purpose is to augment, not replace, human expertise and professional judgment.</p>

                                <hr class="my-4">

                                <h3 class="mt-5" style="font-weight: 600;">1. Principle of Transparency</h3>
                                <p>
                                    <strong>Data Sources:</strong> This system aggregates data from multiple public sources, including NASA FIRMS (MODIS/VIIRS), various weather APIs, and user-submitted field reports. Data is presented to provide situational awareness and is subject to the accuracy and timeliness of the original source.
                                </p>
                                <p>
                                    <strong>AI and Predictive Models:</strong> The predictive models for fire spread and the identification of high-risk areas are generated by an Azure Machine Learning model. These predictions are inherently probabilistic and based on the quality and scope of available data. They are designed as suggestions to aid in strategic planning and should not be interpreted as certainties. Where possible, the system will aim to display confidence levels or other indicators of uncertainty.
                                </p>

                                <h3 class="mt-5" style="font-weight: 600;">2. Principle of Accountability</h3>
                                <p>
                                    <strong>Decision-Making Authority:</strong> ArtemisShield is a tool. It does not make autonomous decisions. The user, as an authorized and trained professional, is solely responsible and accountable for all decisions, actions, and commands made while using information from this dashboard. This includes, but is not limited to, resource deployment, evacuation orders, public alerts, and tactical planning.
                                </p>
                                <p>
                                    <strong>System Responsibility:</strong> We are responsible for the reliable operation of the dashboard and for being transparent about its capabilities and limitations. If you encounter system behavior or data that appears incorrect or inconsistent, you are obligated to report it to the system administrator immediately for review.
                                </p>

                                <h3 class="mt-5" style="font-weight: 600;">3. User Responsibilities</h3>
                                <ul class="list-unstyled">
                                    <li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>You must be authorized personnel to access and use this system.</li>
                                    <li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>You agree to use this system solely for its intended purpose of wildfire management and public protection.</li>
                                    <li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>You must apply your professional judgment when interpreting all data, especially AI-generated predictions.</li>
                                    <li class="mb-2"><i class="fas fa-check-circle text-success me-2"></i>Data entered into the system (e.g., field reports via speech-to-text) must be accurate and truthful to the best of your knowledge.</li>
                                </ul>

                                <h3 class="mt-5" style="font-weight: 600;">4. Disclaimer of Warranty</h3>
                                <p>This dashboard and all its data are provided "as is," without any warranty of any kind, express or implied. We do not guarantee the accuracy, completeness, reliability, or timeliness of any information presented.</p>

                                <h3 class="mt-5" style="font-weight: 600;">5. Limitation of Liability</h3>
                                <p>Under no circumstances shall the creators or maintainers of ArtemisShield be liable for any direct, indirect, incidental, special, or consequential damages resulting from the use or inability to use this service, or from any decisions made or actions taken in reliance upon the information provided by this dashboard.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!--  END: Terms of Service Content  -->

            <!-- Start Footer Area -->
            @include('partials.footer')
            <!-- End Footer Area -->
        </div>
    </div>

    @include('partials.theme_settings')
    @include('partials.scripts')
</body>
</html>